# Generated by Django 5.0.4 on 2024-04-23 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=25)),
                ('f_nickname', models.CharField(max_length=4)),
                ('f_started_year', models.IntegerField()),
                ('f_trophies', models.IntegerField()),
                ('f_logo', models.FileField(upload_to='')),
            ],
        ),
    ]
