# Generated by Django 5.0.4 on 2024-04-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='f_name',
            field=models.CharField(max_length=30),
        ),
    ]
