# Generated by Django 5.0.4 on 2024-04-30 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplapp', '0002_alter_teams_f_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='f_logo',
            field=models.FileField(upload_to='', verbose_name='logos'),
        ),
    ]
